CREATE TABLE "transactions_v2" (
    "Timestamp" TEXT,
    "TwizzlerRating" BIGINT,
    "TwizzlerFrequency" TEXT,
    "Race" TEXT,
    "Gender" TEXT,
    "Income" TEXT,
    "Education" TEXT,
    "SleepHours" DOUBLE PRECISION,
    "WorkHoursPerWeek" BIGINT
);

INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 11:52:01', 4, '<1 per year', 'White', 'Male', '<70k', '<HS', 10.0, 12);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 11:56:32', 1, '<1 per year', 'White', 'Male', '70-130k', 'Bachelor', 9.0, 30);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 11:59:12', 5, '1 per year', 'East Asian', 'Female', '<70k', '<HS', 7.0, 6);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 12:02:17', 1, '<1 per year', 'White', 'Male', '<70k', '<HS', 9.0, 0);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 12:04:48', 2, '1 per month', 'Indian', 'Male', '<70k', '<HS', 8.0, 0);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 12:04:49', 3, '1 per year', 'Indian ', 'Male', '<70k', '<HS', 5.0, 0);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 12:11:29', 3, '<1 per year', 'Middle Eastern', 'Male', '<70k', 'Bachelor', 6.0, 35);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 12:12:48', 5, '<1 per year', 'White', 'Female', '<70k', 'Bachelor', 7.0, 35);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 12:13:16', 3, '1 per year', 'White', 'Female', '<70k', 'Bachelor', 8.0, 40);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 12:18:19', 2, '1 per year', 'White', 'Male', '70-130k', 'Bachelor', 6.0, 40);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 12:20:14', 6, '<1 per year', 'East Asian', 'Female', NULL, 'Bachelor', 6.0, 10);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 12:20:18', 3, '<1 per year', 'East Asian', 'Male', NULL, 'Bachelor', 7.0, 17);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 12:21:09', 1, '<1 per year', 'Hispanic', 'Female', '70-130k', 'Bachelor', 5.0, 3);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 12:26:16', 10, '>1 per day', 'East Asian', 'Female', '<70k', 'HS', 7.0, 0);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 12:26:41', 1, NULL, 'Hispanic', 'Female', '70-130k', '<HS', 5.0, 0);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 12:28:19', 1, '<1 per year', 'East Asian', 'Female', '<70k', '<HS', 7.0, 4);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 12:31:02', 0, '<1 per year', 'Indian', 'Female', '>300k', 'Bachelor', 6.0, 40);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 12:33:37', 10, '>1 per day', 'East Asian', 'Female', '<70k', '<HS', 4.0, 6);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 12:34:57', 1, '1 per year', 'Indian', 'Female', '<70k', '<HS', 5.0, 0);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 12:42:48', 4, '1 per year', 'East Asian', 'Male', '200-300k', 'Bachelor', 8.0, 35);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 12:42:48', 1, '<1 per year', 'East Asian', 'Male', '<70k', 'Masters', 6.0, 0);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 12:46:09', 7, '<1 per year', 'East Asian', 'Female', '<70k', 'HS', 8.0, 27);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 12:46:10', 5, '<1 per year', 'East Asian', 'Female', NULL, 'Bachelor', 8.0, 36);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 12:46:39', 1, '<1 per year', NULL, NULL, '<70k', 'Bachelor', 5.0, 40);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 12:48:01', 0, '<1 per year', 'Indian', 'Male', '>300k', 'Bachelor', 7.0, 50);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 12:50:13', 5, '<1 per year', 'Indian', 'Female', '<70k', '<HS', 7.0, 0);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 12:51:55', 8, '1 per month', 'White', 'Male', '<70k', 'HS', 9.0, 60);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 12:52:35', 2, '<1 per year', 'Southeast Asian', 'Female', '<70k', 'HS', NULL, 20);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 12:52:48', 2, '<1 per year', 'East Asian', 'Male', '<70k', '<HS', 4.0, 0);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 12:56:38', 2, '<1 per year', 'East Asian', 'Male', '<70k', 'HS', 4.0, 0);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 12:56:52', 4, '<1 per year', 'East Asian', 'Female', '<70k', 'Bachelor', 4.0, 0);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 12:57:42', 7, '1 per year', 'White', 'Female', '<70k', 'HS', 6.5, 0);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 13:01:53', 2, '<1 per year', 'East Asian', 'Male', NULL, '<HS', 8.0, 0);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 13:01:54', 1, '1 per year', 'Hispanic', 'Male', '70-130k', 'HS', 3.0, 60);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 13:02:09', 7, '1 per week', 'Southeast Asian', 'Male', '<70k', '<HS', 3.0, 0);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 13:02:46', 4, '1 per year', 'Indian', 'Male', '70-130k', 'Bachelor', 6.5, 40);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 13:04:33', 7, '1 per year', 'East Asian', 'Female', NULL, 'Masters', 5.5, 45);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 13:09:04', 2, '1 per year', 'Southeast Asian', 'Female', '<70k', 'HS', 7.0, 0);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 13:09:40', 1, '1 per year', 'Southeast Asian', 'Male', '<70k', '<HS', 4.0, 0);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 13:12:51', 6, '1 per year', 'White', 'Male', '<70k', 'HS', 6.0, 30);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 13:12:59', 5, '<1 per year', 'White', 'Male', '<70k', 'HS', 6.0, 25);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 13:13:17', 1, '<1 per year', 'Hispanic', 'Male', '<70k', 'HS', 4.0, 0);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 13:13:33', 1, '<1 per year', 'Hispanic', 'Male', '<70k', '<HS', 3.0, 0);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 13:14:39', 2, '<1 per year', 'Indian', 'Female', '<70k', '<HS', 7.0, 2);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 13:14:59', 0, '<1 per year', 'Indian', 'Female', '<70k', '<HS', 6.0, 0);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 13:15:51', 10, '1 per month', 'Hispanic', 'Female', NULL, 'HS', 10.0, 20);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 13:16:37', 2, '<1 per year', 'East Asian', 'Female', '<70k', '<HS', 10.0, 0);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 13:17:43', 2, '1 per year', 'East Asian', 'Female', NULL, 'HS', 7.0, 15);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 13:32:59', 7, '1 per year', 'White', 'Female', NULL, 'PhD', 8.0, 60);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 14:04:17', 7, '1 per year', 'Indian', 'Female', '<70k', 'HS', 7.0, 15);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 14:05:28', 6, '1 per month', 'White', 'Male', '130-200k', 'HS', 7.0, 3);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 14:17:31', 5, '1 per month', 'Indian', 'Male', '<70k', '<HS', 8.0, 0);
INSERT INTO "transactions_v2" ("Timestamp", "TwizzlerRating", "TwizzlerFrequency", "Race", "Gender", "Income", "Education", "SleepHours", "WorkHoursPerWeek") VALUES ('6/13/2025 14:24:31', 6, '>1 per week', 'Indian', 'Non-Binary', '<70k', '<HS', 6.0, 11);